### ISSUE TITLE
python_install_on_site_not working

### ISSUE THREAD

**Issue by olivier-stasse** [ComePerrot/talos_manipulation#13]
Dear @ComePerrot,
The repository seems to fail during the cmake processing step with:
```
CMake Error at python/CMakeLists.txt:34 (python_install_on_site):
Unknown CMake command "python_install_on_site".
```

at commit: 78d55cedbde8

I had to update the [jrl-cmake-modules](https://github.com/jrl-umi3218/jrl-cmake-modules) and to include ```python.cmake```

**Comment by ComePerrot** [comment]
Merged https://github.com/ComePerrot/talos-manipulation/pull/14, so this issue should now be fixed.
Thank you for the fixes you proposed.

Fixes were already made on the branch https://github.com/ComePerrot/talos-manipulation/tree/topic/test but were not propagated to back to the devel, sorry about that.
